project: medea-area-51
regions:
  run: us-central1
  scheduler: us-east1

graph:
  training-ground: {a1: training-ground-ctl}

origins:
  training-ground:
    schedule: '1 1 1 1 1'
  training-ground-ctl:
    schedule: '15 */6 * * *'
    input: >
      {
          "submit-tasks": {
              "problemlist": "ALL",
              "solverlist": "ALL"
          }
      }
    retry-count: 3

services:
  training-ground:
    memory: 4Gi
    timeout: 900s
  training-ground-ctl:
  training-ground-ui:
